on:
  workflow_dispatch:
  schedule:
  - cron: '25 */6 * * *'
  push:
    branches: ['main']
  
jobs:
  sync-rss:
    name: Skeeter Deleter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: false
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Install python requirements
      run: |
        sudo apt-get install libmagic1
        pip install -r requirements.txt
        mkdir archive

    - name: Purge skeets
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: |
        python skeeter_deleter.py -s 2 -v -y